import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import { fonts } from './font'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import Navbar from '@/component/navbar'


export default function RootLayout({ children }) {
  return (
    <html lang='en' >
      <body className={fonts.rubik.className}>
        <Providers>
          <>
            <Navbar />

            {
              children}
          </>
        </Providers>

      </body>
    </html>
  )
}
